#!/usr/bin/env python3
"""Arctis Engine — March 2026 Profitability Analysis"""
import psycopg2
from datetime import timedelta

conn = psycopg2.connect('postgres://algorivo:algorivo_dev@localhost:5532/algorivo')
cur = conn.cursor()

# Get all trading days
cur.execute("SELECT DISTINCT ts::date FROM candles WHERE symbol='NQM6' ORDER BY ts::date")
days = [r[0] for r in cur.fetchall()]

print("=" * 60)
print("  ARCTIS ENGINE — MARCH 2026 PROFITABILITY REPORT")
print("=" * 60)
print(f"\nData Range: {days[0]} to {days[-1]} ({len(days)} trading days)")
print(f"Symbols: NQM6, ESM6")
print()

for symbol in ['NQM6', 'ESM6']:
    print(f"\n{'='*60}")
    print(f"  {symbol} ANALYSIS")
    print(f"{'='*60}")

    total_signals = 0
    wins = 0
    losses = 0
    total_pnl = 0.0
    trades = []

    for day in days:
        next_day = day + timedelta(days=1)
        cur.execute("""
            SELECT ts, o, h, l, c, volume
            FROM candles
            WHERE symbol=%s AND ts >= %s AND ts < %s AND timeframe='1m'
            ORDER BY ts
        """, (symbol, day, next_day))
        bars = cur.fetchall()
        if len(bars) < 100:
            continue

        # Opening Range (first 30 min = 30 bars)
        or_bars = bars[:30]
        or_high = max(float(b[2]) for b in or_bars)
        or_low = min(float(b[3]) for b in or_bars)

        # Find first OR breakout after bar 30
        breakout_bar = None
        breakout_dir = None

        for i, bar in enumerate(bars[30:], 30):
            if float(bar[2]) > or_high:
                breakout_bar = i
                breakout_dir = 'LONG'
                break
            if float(bar[3]) < or_low:
                breakout_bar = i
                breakout_dir = 'SHORT'
                break

        if breakout_bar is None or breakout_dir is None:
            continue

        total_signals += 1

        if breakout_dir == 'LONG':
            entry = or_high
            stop = or_low
            target = entry + (entry - stop) * 2  # 2R target

            hit_target = False
            hit_stop = False
            for bar in bars[breakout_bar:]:
                if float(bar[3]) <= stop:
                    hit_stop = True
                    break
                if float(bar[2]) >= target:
                    hit_target = True
                    break

            if hit_target:
                wins += 1
                pnl = target - entry
            else:
                losses += 1
                pnl = -(entry - stop)
        else:
            entry = or_low
            stop = or_high
            target = entry - (stop - entry) * 2

            hit_target = False
            hit_stop = False
            for bar in bars[breakout_bar:]:
                if float(bar[2]) >= stop:
                    hit_stop = True
                    break
                if float(bar[3]) <= target:
                    hit_target = True
                    break

            if hit_target:
                wins += 1
                pnl = entry - target
            else:
                losses += 1
                pnl = -(stop - entry)

        total_pnl += pnl
        trades.append({
            'day': str(day),
            'dir': breakout_dir,
            'result': 'WIN' if (hit_target if breakout_dir == 'LONG' else hit_target) else 'LOSS',
            'pnl': round(pnl, 2)
        })

    wr = (wins / total_signals * 100) if total_signals > 0 else 0
    avg_win = sum(t['pnl'] for t in trades if t['result'] == 'WIN') / max(wins, 1)
    avg_loss = abs(sum(t['pnl'] for t in trades if t['result'] == 'LOSS') / max(losses, 1))
    pf = (avg_win * wins) / (avg_loss * losses) if losses > 0 and avg_loss > 0 else float('inf')

    tick_value = 5.0 if 'NQ' in symbol else 12.5
    dollar_pnl = total_pnl / 0.25 * tick_value

    print(f"\n  Total Signals:    {total_signals}")
    print(f"  Wins:             {wins} ({wr:.1f}%)")
    print(f"  Losses:           {losses}")
    print(f"  Avg Win:          {avg_win:.2f} pts")
    print(f"  Avg Loss:         {avg_loss:.2f} pts")
    print(f"  Profit Factor:    {pf:.2f}")
    print(f"  Total P&L:        {total_pnl:+.2f} pts ({dollar_pnl:+.0f} USD)")
    print(f"\n  Trade Log:")
    for t in trades:
        print(f"    {t['day']}  {t['dir']:5s}  {t['result']:4s}  {t['pnl']:+8.2f} pts")

print(f"\n{'='*60}")
print("  CONCLUSION")
print(f"{'='*60}")
print("\n  Report generated by Arctis Engine Backtest v1.0")

cur.close()
conn.close()
